comment:
  require_changes: true
  layout: "diff, files"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: auto
        threshold: 2%

flag_management:
  individual_flags:
    - name: python_backend
      paths:
        - nc_py_api/
    - name: php_backend
      paths:
        - lib/
    - name: frontend
      paths:
        - src/

fixes:
  - "apps/cloud_py_api/::"
