name: (Py)Build and Publish to PyPi

on:
  workflow_dispatch:

env:
  TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
  TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  TWINE_PYPI_ARGS: ""

jobs:

  wheels:
    name: Build sdist and wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Preparations
        run: python3 -m pip install check-manifest twine build wheel

      - name: Build
        run: |
          python3 -m check_manifest
          python3 -m build

      - name: Check
        run: twine check dist/*

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist/*.*
          if-no-files-found: error

  publish:
    name: Publish to Pypi
    needs: [wheels]
    runs-on: ubuntu-latest

    steps:
    - name: Collect sdist and wheels
      uses: actions/download-artifact@v3
      with:
        name: wheels
        path: dist

    - name: Publish wheels to PyPI
      run: |
          python3 -m pip install twine
          ls -la dist/
          twine upload ${{ env.TWINE_PYPI_ARGS }} --skip-existing dist/*.whl
          twine upload ${{ env.TWINE_PYPI_ARGS }} dist/*tar.gz
